// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(PostsDbContext))]
    [Migration("20220518092414_InitialSQLite")]
    partial class InitialSQLite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Domain.EmailSubscription", b =>
                {
                    b.Property<Guid>("User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("User");

                    b.ToTable("EmailSubscriptions");
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.HasIndex("Audience");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.PostAudienceGroup", b =>
                {
                    b.Property<int>("AudienceGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudienceGroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FacultyFilter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenerationFilter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleFilter")
                        .HasColumnType("INTEGER");

                    b.HasKey("AudienceGroupID");

                    b.ToTable("AudienceGroups");
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.HasOne("Domain.PostAudienceGroup", "AudienceGroup")
                        .WithMany("Posts")
                        .HasForeignKey("Audience")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudienceGroup");
                });

            modelBuilder.Entity("Domain.PostAudienceGroup", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
